# https://github.com/lguzzon-DOCKER/docker-cordova/blob/develop/Dockerfile
# https://raw.githubusercontent.com/lguzzon-DOCKER/docker-cordova/develop/Dockerfile

# https://github.com/lguzzon-scratchbook/cordova-web-wrap/blob/feature/abotLucaGuzzon/buildReleaseApk.sh
# https://raw.githubusercontent.com/lguzzon-scratchbook/cordova-web-wrap/feature/abotLucaGuzzon/buildReleaseApk.sh

# https://github.com/youstinus/volunteer/blob/master/.travis.yml
# https://raw.githubusercontent.com/youstinus/volunteer/master/.travis.yml

# https://docs.travis-ci.com/user/languages/android/
