# https://github.com/lguzzon-DOCKER/docker-cordova/blob/develop/Dockerfile
# https://raw.githubusercontent.com/lguzzon-DOCKER/docker-cordova/develop/Dockerfile

# https://github.com/lguzzon-scratchbook/cordova-web-wrap/blob/feature/abotLucaGuzzon/buildReleaseApk.sh
# https://raw.githubusercontent.com/lguzzon-scratchbook/cordova-web-wrap/feature/abotLucaGuzzon/buildReleaseApk.sh

# https://github.com/youstinus/volunteer/blob/master/.travis.yml
# https://raw.githubusercontent.com/youstinus/volunteer/master/.travis.yml

# https://docs.travis-ci.com/user/languages/android/

os: linux
dist: xenial
language: node_js
branches:
  only:
  - /.*/

jobs:
  include:
  -
    language: android
    os: linux
    dist: xenial
    jdk: oraclejdk8
    android:
      components:
      - tools
      - platform-tools
      - build-tools-29.0.3
      - android-27
      - android-28
      - android-29
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
      licenses:
      - android-sdk-preview-license-.+
      - android-sdk-license-.+
      - android-googletv-license-.+
      - google-gdk-license-.+
      - intel-android-extra-license-.+
      - mips-android-sysimage-license-.+
    before_install:
    - export LANG=en_US.UTF-8
    - sudo apt update
    #- sudo apt upgrade -y
    # SDKMAN
    - sudo apt install -y curl wget unzip zip ca-certificates 
    - curl -s "https://get.sdkman.io" | bash
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - echo sdkman_auto_answer=true > "$HOME/.sdkman/etc/config"
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - sdk version
	# ANT
    - sdk install ant
    - ant -version
	# MAVEN
    - sdk install maven
    - mvn -version
    - nvm install "12.18.1"
    - node --version
    - npm --version
    - npm i -g --unsafe-perm=true --allow-root "cordova@latest"
    - cordova --version
    - cordova telemetry off
    - npm i -g --unsafe-perm=true --allow-root "phonegap@latest"
    - phonegap --version
    - phonegap analytics off
    - npm i -g --unsafe-perm=true --allow-root "@ionic/cli@latest"
    - ionic --version
    - npm i -g --unsafe-perm=true --allow-root "framework7-cli@latest"
    - framework7 --version
    - npm i -g --unsafe-perm=true --allow-root "cordova-check-plugins@latest"
    - cordova-check-plugins --version
    install:
    - (cordova platform add android || true)
    - cordova requirements android
    - cordova prepare
    - cordova build android --release
    - (rm keystore.PKCS12 || true)
    - keytool -genkey -alias aliasKeystore -keyalg RSA -keystore ./keystore.PKCS12 -dname "CN=Luca Guzzon, OU=Mobilez, O=SolonSoft, L=Siena, S=Toscana, C=IT" -storepass storepass1qaz2wsX  -keysize 4096  -validity 10000 -deststoretype pkcs12
    - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.PKCS12 -storepass storepass1qaz2wsX ./platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk aliasKeystore
    - (rm release.apk || true)
    - $(find / -iname zipalign 2>/dev/null | head -1) -v 4 ./platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk release.apk
    - sudo chown -R $(whoami):$(whoami) .
    - sudo chown -R $(whoami):$(whoami) *
    before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name "Luca Guzzon"
    - git config --local user.email "luca.guzzon@gmail.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - mv release.apk "${TRAVIS_TAG}-release.apk"
    - git tag $TRAVIS_TAG
    deploy:
      provider: releases
      username: "$U"
      password: "$P"
      file: "${TRAVIS_TAG}-release.apk"
      cleanup: false
